"""Initial schema: all tables

Revision ID: 7d41388c6b60
Revises: 
Create Date: 2026-06-13 16:09:25.562393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d41388c6b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('badge_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATIONS_CENTER', 'FIREFIGHTER', 'DISPATCHER', name='userrole'), nullable=False),
    sa.Column('leave_status', sa.Enum('ON_DUTY', 'ON_LEAVE', 'SICK', 'ON_MISSION', name='leavestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_known_latitude', sa.Float(), nullable=True),
    sa.Column('last_known_longitude', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('device_push_token', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('call_sign', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('FIRE_TRUCK', 'WATER_TANKER', 'LADDER_TRUCK', 'RESCUE_VEHICLE', 'COMMAND_VEHICLE', 'AMBULANCE', 'HAZMAT', 'OTHER', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'DEPLOYED', 'MAINTENANCE', 'RETIRED', name='vehiclestatus'), nullable=False),
    sa.Column('water_capacity_liters', sa.Integer(), nullable=True),
    sa.Column('crew_capacity', sa.Integer(), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('gps_updated_at', sa.DateTime(), nullable=True),
    sa.Column('home_station', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sign'),
    sa.UniqueConstraint('plate_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_status'), ['status'], unique=False)

    op.create_table('crew_members',
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('crew_id', 'user_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=True),
    sa.Column('incident_type', sa.Enum('STRUCTURE_FIRE', 'WILDFIRE', 'VEHICLE_FIRE', 'TECHNICAL_RESCUE', 'HAZMAT', 'WATER_RESCUE', 'MEDICAL_ASSIST', 'FALSE_ALARM', 'PREVENTIVE', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'ON_SCENE', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', name='incidentstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('caller_phone', sa.String(length=20), nullable=True),
    sa.Column('caller_name', sa.String(length=100), nullable=True),
    sa.Column('hazard_notes', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('on_scene_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_crew_id', sa.Integer(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_crew_id'], ['crews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_assigned_crew_id'), ['assigned_crew_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_reference_number'), ['reference_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_crew_id'), ['crew_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'TEMPLATE', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('read_by_user_ids', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('sos_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firefighter_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='sosalertstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firefighter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_alerts_firefighter_id'), ['firefighter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_alerts_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('FIREFIGHTING', 'EVACUATION', 'SEARCH_RESCUE', 'PERIMETER_CONTROL', 'VENTILATION', 'WATER_DELIVERY', 'FUEL_DELIVERY', 'EQUIPMENT_DELIVERY', 'PERSONNEL_TRANSPORT', 'DOCUMENTATION', 'DEBRIEF', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_notes', sa.String(length=255), nullable=True),
    sa.Column('due_by', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('assigned_crew_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_crew_id'], ['crews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_crew_id'), ['assigned_crew_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_incident_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_crew_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sos_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_sos_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_sos_alerts_firefighter_id'))

    op.drop_table('sos_alerts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_incident_id'))

    op.drop_table('messages')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_is_active'))
        batch_op.drop_index(batch_op.f('ix_shifts_crew_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_reference_number'))
        batch_op.drop_index(batch_op.f('ix_incidents_assigned_crew_id'))

    op.drop_table('incidents')
    op.drop_table('crew_members')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_status'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('crews')
    # ### end Alembic commands ###
